version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run:
          name: bundle install
          command: "bundle install"
      - run:
          name: Build the site
          command: "bundle exec rake build"
          store_artifacts:
            path: "_site"
            prefix: "site"
